import { Interest, Signal, Notification, TrendingTopic, Source } from '@/types';

export const INTERESTS: Interest[] = [
  { id: '1', name: 'Tech', emoji: '💻', imageUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800&auto=format&fit=crop' },
  { id: '2', name: 'Finance', emoji: '💰', imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=800&auto=format&fit=crop' },
  // Removed K-Pop interest from onboarding/category list
  { id: '4', name: 'Local Events', emoji: '🎪', imageUrl: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=800&auto=format&fit=crop' },
  { id: '5', name: 'Science', emoji: '🔬', imageUrl: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?q=80&w=800&auto=format&fit=crop' },
  { id: '6', name: 'Sports', emoji: '⚽', imageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?q=80&w=800&auto=format&fit=crop' },
  { id: '7', name: 'Food', emoji: '🍜', imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800&auto=format&fit=crop' },
  { id: '8', name: 'Travel', emoji: '✈️', imageUrl: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?q=80&w=800&auto=format&fit=crop' },
  { id: '9', name: 'Gaming', emoji: '🎮', imageUrl: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=800&auto=format&fit=crop' },
  { id: '10', name: 'Fashion', emoji: '👗', imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=800&auto=format&fit=crop' },
  { id: '11', name: 'Health', emoji: '🏥', imageUrl: 'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?q=80&w=800&auto=format&fit=crop' },
  { id: '12', name: 'Music', emoji: '🎸', imageUrl: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?q=80&w=800&auto=format&fit=crop' },
];

export const SOURCES: Source[] = [
  { id: '1', name: 'TechCrunch', verified: true, url: 'https://techcrunch.com' },
  { id: '2', name: 'The Verge', verified: true, url: 'https://theverge.com' },
  { id: '3', name: 'Bloomberg', verified: true, url: 'https://bloomberg.com' },
  { id: '4', name: 'Naver News', verified: true, url: 'https://news.naver.com' },
  { id: '5', name: 'Allkpop', verified: true, url: 'https://allkpop.com' },
  { id: '6', name: 'Soompi', verified: true, url: 'https://soompi.com' },
  { id: '7', name: 'Reddit', verified: false, url: 'https://reddit.com' },
  { id: '8', name: 'Twitter', verified: false, url: 'https://twitter.com' },
];

export const MOCK_SIGNALS: Signal[] = [
  {
    id: '1',
    title: 'Apple announces new Vision Pro features at WWDC',
    summary: 'Apple unveiled significant updates to Vision Pro including improved hand tracking and new productivity apps designed for spatial computing.',
    content: 'Apple unveiled significant updates to Vision Pro including improved hand tracking and new productivity apps designed for spatial computing.\n\nThe new features include enhanced gesture recognition that allows users to interact with virtual objects more naturally. Apple demonstrated how users can now pinch, swipe, and manipulate 3D objects with unprecedented precision.\n\nAdditionally, the company announced partnerships with major software developers to bring professional-grade applications to the Vision Pro platform. These include 3D modeling tools, collaborative workspaces, and immersive creative applications.\n\nThe updates will be available as part of visionOS 2.0, rolling out to all Vision Pro users in the coming months.',
    sourceId: '1',
    sourceName: 'TechCrunch',
    verified: true,
    tags: ['Tech', 'Apple', 'VR'],
    url: 'https://techcrunch.com',
    relevanceScore: 0.95,
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    imageUrl: 'https://images.unsplash.com/photo-1585218333001-4a00b1a3a8f9?q=80&w=1200&auto=format&fit=crop',
    saved: false,
    liked: false,
  },
  {
    id: '2',
    title: 'BTS announces surprise comeback album',
    summary: 'The global K-pop sensation BTS revealed plans for a new album release next month, sending fans into a frenzy across social media.',
    content: 'The global K-pop sensation BTS revealed plans for a new album release next month, sending fans into a frenzy across social media.\n\nIn a surprise announcement during their latest livestream, the seven-member group confirmed they have been working on new music throughout the year. The album, their first group project in over 18 months, will feature collaborations with renowned producers and artists from around the world.\n\nFans, known as ARMY, immediately trended multiple hashtags worldwide, with #BTSComeback reaching the top spot within minutes. Pre-order information and the official release date are expected to be announced in the coming days.',
    sourceId: '5',
    sourceName: 'Allkpop',
    verified: true,
    tags: ['K-Pop', 'BTS', 'Music'],
    url: 'https://allkpop.com',
    relevanceScore: 0.92,
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    imageUrl: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?q=80&w=1200&auto=format&fit=crop',
    saved: false,
    liked: false,
  },
  {
    id: '3',
    title: 'Bitcoin surges past $50K on ETF approval news',
    summary: 'Cryptocurrency markets rallied today as major financial institutions received approval to launch Bitcoin ETFs, marking a significant milestone.',
    content: 'Cryptocurrency markets rallied today as major financial institutions received approval to launch Bitcoin ETFs, marking a significant milestone for digital asset adoption.\n\nBitcoin jumped more than 12% in early trading, breaking through the $50,000 barrier for the first time since 2022. The surge followed the U.S. Securities and Exchange Commission\'s decision to approve applications from several major asset managers.\n\nIndustry experts believe this approval will open the floodgates for institutional investment, potentially bringing billions of dollars into the cryptocurrency market.',
    sourceId: '3',
    sourceName: 'Bloomberg',
    verified: true,
    tags: ['Finance', 'Crypto', 'Bitcoin'],
    url: 'https://bloomberg.com',
    relevanceScore: 0.88,
    timestamp: new Date(Date.now() - 1000 * 60 * 60),
    imageUrl: 'https://images.unsplash.com/photo-1621416894569-0f39b4b8e1bc?q=80&w=1200&auto=format&fit=crop',
    saved: false,
    liked: false,
  },
  {
    id: '4',
    title: 'Seoul announces major tech hub development',
    summary: 'The Seoul Metropolitan Government unveiled plans for a new technology hub in Gangnam, attracting global tech companies and startups.',
    sourceId: '4',
    sourceName: 'Naver News',
    verified: true,
    tags: ['Local Events', 'Tech', 'Seoul'],
    url: 'https://news.naver.com',
    relevanceScore: 0.85,
    timestamp: new Date(Date.now() - 1000 * 60 * 90),
    imageUrl: 'https://images.unsplash.com/photo-1526483360412-f4dbaf036963?q=80&w=1200&auto=format&fit=crop',
    saved: false,
    liked: false,
  },
  {
    id: '5',
    title: 'AI startup raises $100M Series B',
    summary: 'A Korean AI startup focused on language models secured $100M in Series B funding led by top venture capital firms.',
    sourceId: '1',
    sourceName: 'TechCrunch',
    verified: true,
    tags: ['Tech', 'AI', 'Startup'],
    url: 'https://techcrunch.com',
    relevanceScore: 0.82,
    timestamp: new Date(Date.now() - 1000 * 60 * 120),
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=1200&auto=format&fit=crop',
    saved: false,
    liked: false,
  },
  {
    id: '6',
    title: 'Premier League: Late winner seals derby classic',
    summary: 'A stoppage-time goal delivered a dramatic win in the city derby, keeping the title race alive.',
    sourceId: '2',
    sourceName: 'The Verge',
    verified: true,
    tags: ['Sports'],
    url: 'https://theverge.com',
    relevanceScore: 0.78,
    timestamp: new Date(Date.now() - 1000 * 60 * 180),
    imageUrl: 'https://images.unsplash.com/photo-1508261303786-0e3b64e66c25?q=80&w=1200&auto=format&fit=crop',
    saved: false,
    liked: false,
  },
  {
    id: '7',
    title: 'New study links sleep to memory consolidation',
    summary: 'Researchers found deeper connections between REM sleep cycles and long-term memory formation.',
    sourceId: '3',
    sourceName: 'Bloomberg',
    verified: true,
    tags: ['Health', 'Science'],
    url: 'https://bloomberg.com',
    relevanceScore: 0.76,
    timestamp: new Date(Date.now() - 1000 * 60 * 240),
    imageUrl: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=1200&auto=format&fit=crop',
    saved: false,
    liked: false,
  },
  {
    id: '8',
    title: 'Local bakery wins design award for sourdough',
    summary: 'The neighborhood favorite received international recognition for innovation in artisan baking.',
    sourceId: '7',
    sourceName: 'Reddit',
    verified: false,
    tags: ['Food', 'Local'],
    url: 'https://reddit.com',
    relevanceScore: 0.7,
    timestamp: new Date(Date.now() - 1000 * 60 * 360),
    imageUrl: 'https://images.unsplash.com/photo-1549931319-ec04f94a04d3?q=80&w=1200&auto=format&fit=crop',
    saved: false,
    liked: false,
  },
  {
    id: '9',
    title: 'Electric cars hit new sales record in Q2',
    summary: 'EV adoption accelerates as charging networks expand across major cities.',
    sourceId: '2',
    sourceName: 'The Verge',
    verified: true,
    tags: ['Tech', 'EV'],
    url: 'https://theverge.com',
    relevanceScore: 0.74,
    timestamp: new Date(Date.now() - 1000 * 60 * 410),
    imageUrl: 'https://images.unsplash.com/photo-1542365887-0371d1f1c4f1?q=80&w=1200&auto=format&fit=crop',
    saved: false,
    liked: false,
  },
  {
    id: '10',
    title: 'Indie game tops charts after surprise drop',
    summary: 'A cozy sim from a two-person studio is the week’s most downloaded title.',
    sourceId: '7',
    sourceName: 'Reddit',
    verified: false,
    tags: ['Gaming', 'Indie'],
    url: 'https://reddit.com',
    relevanceScore: 0.69,
    timestamp: new Date(Date.now() - 1000 * 60 * 480),
    imageUrl: 'https://images.unsplash.com/photo-1587840171670-8b850147754e?q=80&w=1200&auto=format&fit=crop',
    saved: false,
    liked: false,
  },
  {
    id: '11',
    title: 'New café opens with AI-powered ordering',
    summary: 'Robot baristas and personalized menus draw lines around the block.',
    sourceId: '1',
    sourceName: 'TechCrunch',
    verified: true,
    tags: ['AI', 'Food'],
    url: 'https://techcrunch.com',
    relevanceScore: 0.71,
    timestamp: new Date(Date.now() - 1000 * 60 * 520),
    imageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=1200&auto=format&fit=crop',
    saved: false,
    liked: false,
  },
  {
    id: '12',
    title: 'Art museum debuts interactive projection exhibit',
    summary: 'Immersive rooms blend motion tracking with generative visuals.',
    sourceId: '2',
    sourceName: 'The Verge',
    verified: true,
    tags: ['Art', 'Tech'],
    url: 'https://theverge.com',
    relevanceScore: 0.68,
    timestamp: new Date(Date.now() - 1000 * 60 * 560),
    imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=1200&auto=format&fit=crop',
    saved: false,
    liked: false,
  },
  {
    id: '13',
    title: 'Startup launches pocket translator for 70 languages',
    summary: 'Real‑time on-device translation without internet connectivity.',
    sourceId: '3',
    sourceName: 'Bloomberg',
    verified: true,
    tags: ['Gadgets', 'AI'],
    url: 'https://bloomberg.com',
    relevanceScore: 0.72,
    timestamp: new Date(Date.now() - 1000 * 60 * 600),
    imageUrl: 'https://images.unsplash.com/photo-1518779578993-ec3579fee39f?q=80&w=1200&auto=format&fit=crop',
    saved: false,
    liked: false,
  },
  {
    id: '14',
    title: 'Beach cleanup removes 5 tons of trash in one day',
    summary: 'Volunteers and local orgs team up to restore the coastline.',
    sourceId: '4',
    sourceName: 'Naver News',
    verified: true,
    tags: ['Local', 'Environment'],
    url: 'https://news.naver.com',
    relevanceScore: 0.66,
    timestamp: new Date(Date.now() - 1000 * 60 * 720),
    imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200&auto=format&fit=crop',
    saved: false,
    liked: false,
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: '1',
    title: 'Breaking: Apple Event',
    message: 'Apple announces new Vision Pro features',
    category: 'Tech',
    urgency: 'high',
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    read: false,
    signalId: '1',
  },
  {
    id: '2',
    title: 'BTS Comeback Alert',
    message: 'New album announcement from BTS',
    category: 'K-Pop',
    urgency: 'medium',
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    read: false,
    signalId: '2',
  },
  {
    id: '3',
    title: 'Market Update',
    message: 'Bitcoin surges past $50K',
    category: 'Finance',
    urgency: 'medium',
    timestamp: new Date(Date.now() - 1000 * 60 * 60),
    read: true,
    signalId: '3',
  },
  {
    id: '4',
    title: 'Order Tweaked!',
    message: 'Added Gourmet Cheese to your kit. Next week just got tastier!',
    category: 'Order',
    urgency: 'low',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4),
    read: true,
  },
  {
    id: '5',
    title: 'Weekend Bonus!',
    message: 'Get 10% off on a surprise side for your next order. Yum!',
    category: 'Bonus',
    urgency: 'low',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
    read: false,
  },
];

export const TRENDING_TOPICS: TrendingTopic[] = [
  // Tech
  { id: '1', name: 'Vision Pro', count: 12500, category: 'Tech' },
  { id: '5', name: 'AI Funding', count: 3200, category: 'Tech' },
  { id: '9', name: 'ChatGPT 5', count: 18900, category: 'Tech' },
  { id: '14', name: 'iPhone 16', count: 24300, category: 'Tech' },
  
  // Finance
  { id: '3', name: 'Bitcoin ETF', count: 8900, category: 'Finance' },
  { id: '10', name: 'Stock Market Rally', count: 7800, category: 'Finance' },
  { id: '15', name: 'Fed Interest Rates', count: 9200, category: 'Finance' },
  
  // K-Pop
  { id: '2', name: 'BTS Comeback', count: 45000, category: 'K-Pop' },
  { id: '11', name: 'Blackpink World Tour', count: 32000, category: 'K-Pop' },
  { id: '16', name: 'NewJeans Debut', count: 28500, category: 'K-Pop' },
  
  // Sports
  { id: '6', name: 'Premier League', count: 21400, category: 'Sports' },
  { id: '12', name: 'NBA Finals', count: 19800, category: 'Sports' },
  { id: '17', name: 'World Cup Qualifiers', count: 16700, category: 'Sports' },
  
  // Health
  { id: '7', name: 'Sleep Science', count: 6300, category: 'Health' },
  { id: '13', name: 'Mental Health Awareness', count: 8100, category: 'Health' },
  { id: '18', name: 'Weight Loss Study', count: 5400, category: 'Health' },
  
  // Science
  { id: '19', name: 'Mars Mission', count: 11200, category: 'Science' },
  { id: '20', name: 'Climate Change Report', count: 9600, category: 'Science' },
  { id: '21', name: 'Quantum Computing', count: 7300, category: 'Science' },
  
  // Food
  { id: '22', name: 'Michelin Stars 2024', count: 4800, category: 'Food' },
  { id: '23', name: 'Plant-Based Trends', count: 6200, category: 'Food' },
  { id: '24', name: 'Korean Street Food', count: 5100, category: 'Food' },
  
  // Gaming
  { id: '25', name: 'GTA 6 Release', count: 42000, category: 'Gaming' },
  { id: '26', name: 'Esports Championship', count: 15300, category: 'Gaming' },
  { id: '27', name: 'Nintendo Switch 2', count: 19400, category: 'Gaming' },
  
  // Fashion
  { id: '28', name: 'Paris Fashion Week', count: 13700, category: 'Fashion' },
  { id: '29', name: 'Sustainable Fashion', count: 7900, category: 'Fashion' },
  { id: '30', name: 'Y2K Comeback', count: 9300, category: 'Fashion' },
  
  // Travel
  { id: '31', name: 'Best Destinations 2024', count: 8600, category: 'Travel' },
  { id: '32', name: 'Digital Nomad Visas', count: 6700, category: 'Travel' },
  { id: '33', name: 'Solo Travel Safety', count: 5900, category: 'Travel' },
  
  // Music
  { id: '34', name: 'Grammy Awards', count: 17200, category: 'Music' },
  { id: '35', name: 'Taylor Swift Tour', count: 29800, category: 'Music' },
  { id: '36', name: 'Hip Hop Revival', count: 8400, category: 'Music' },
  
  // Local Events
  { id: '4', name: 'Seoul Tech Hub', count: 5600, category: 'Local Events' },
  { id: '37', name: 'City Festival', count: 4300, category: 'Local Events' },
  { id: '38', name: 'Community Cleanup', count: 3200, category: 'Local Events' },
];
